<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModulesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // can't use factory because data is custom not random
        // $modules = factory(Module::class)->create();

        DB::table('modules')->insert([
            [
                'name' => 'Dashboard',
                'description' => 'Home/Dashboard',
                'url' => '/',
                'is_module' => 1,
                'is_child' => 0,
                'menu_parent_id' => 0,
                'icon' => 'fa fa-home',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Clients',
                'description' => 'Clients',
                'url' => '/',
                'is_module' => 0,
                'is_child' => 0,
                'menu_parent_id' => 0,
                'icon' => 'fa fa-user',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Reservations',
                'description' => 'Reservations',
                'url' => '/reservations',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 2,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Doc Submissions',
                'description' => 'Doc Submissions',
                'url' => '/doc_submissions',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 2,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Monitoring',
                'description' => 'Monitoring',
                'url' => '/',
                'is_module' => 0,
                'is_child' => 0,
                'menu_parent_id' => 0,
                'icon' => 'fa fa-line-chart',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Equity',
                'description' => 'Equity',
                'url' => '/equity',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'CTS',
                'description' => 'CTS',
                'url' => '/cts',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'EWT',
                'description' => 'EWT',
                'url' => '/ewt',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Bank Take Out',
                'description' => 'Bank Take Out',
                'url' => '/bank_take_out',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Notice for Rescissions',
                'description' => 'Notice for Rescissions',
                'url' => '/notice_for_rescissions',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'DOAS & DST',
                'description' => 'DOAS & DST',
                'url' => '/doas',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'CAR Processing',
                'description' => 'CAR Processing',
                'url' => '/car_processing',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'RD Assestment',
                'description' => 'RD Assestment',
                'url' => '/rd_assestment',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Titling & Tax Declaration',
                'description' => 'Titling & Tax Declaration',
                'url' => '/titling_and_tax_dec',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 5,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Maintenance',
                'description' => 'Maintenance',
                'url' => '/',
                'is_module' => 0,
                'is_child' => 0,
                'menu_parent_id' => 0,
                'icon' => 'fa fa-cogs',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Projects',
                'description' => 'Projects',
                'url' => '/projects',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'House/Units',
                'description' => 'House/Units',
                'url' => '/house_units',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Unit Types',
                'description' => 'Unit Types',
                'url' => '/unit_types',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Prospects',
                'description' => 'Prospects',
                'url' => '/prospects',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Brokers',
                'description' => 'Brokers',
                'url' => '/brokers',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Roles',
                'description' => 'Roles',
                'url' => '/roles',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Logs',
                'description' => 'Logs',
                'url' => '/logs',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 15,
                'icon' => '',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Payments',
                'description' => 'Payments',
                'url' => '/payments',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 0,
                'icon' => 'fa fa-money',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            [
                'name' => 'Users',
                'description' => 'Users',
                'url' => '/users',
                'is_module' => 1,
                'is_child' => 1,
                'menu_parent_id' => 0,
                'icon' => 'fa fa-users',
                'status' => 1,
                'created_by' => 1, 
                'updated_by' => 1,
                'created_date' => now(), 
                'updated_date' => now(),
                'deleted_at' => NULL
            ],
            // end, 24 records
        ]);
    }
}
